### ISSUE TITLE
How can I run in a simulation?

### ISSUE THREAD

**Issue by mincheulkim** [LeeKeyu/sarl_star#2]
Hello, I'm very impressed with your work. I have completely installed the code according the instruction. Can I run your code in a simulation environment instead of a real world?

Thanks,

**Comment by LeeKeyu** [comment]
Hi,
Since our code is developed for lidar-based 2D navigation and implemented on TurtleBot, you can feel free to adapt it to some off-the-shelf simulators for turtlebot (e.g. [Stage](http://wiki.ros.org/turtlebot_stage)). Since the simulator and our platform is only different in the sources of sensor data, the navigation algorithm should work fine.

However, I am not sure whether these simulators can provide dynamic obstacles in the environment to simulate the humans, and you may need to implement the simulated crowd by yourself.

Regards,
Keyu

**Comment by LeeKeyu** [comment]
closed.

**Comment by MandyZhang4869** [comment]
Have you succeded？I also want to run it in a simulation environment.
